"use client"

import { PageLayout } from "@/components/landing/page-layout"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import {
  Brain,
  Activity,
  Shield,
  TrendingUp,
  Calendar,
  Users,
  ArrowRight,
  CheckCircle2,
  BarChart3,
  Zap,
  Target,
  HeartPulse,
  AlertTriangle,
  LineChart,
  RefreshCw,
  UserCheck,
  MonitorSmartphone,
} from "lucide-react"

const featureCategories = [
  {
    icon: Brain,
    title: "AI Personalization",
    gradient: "from-primary to-primary/50",
    description:
      "Every training plan is uniquely generated by our AI engine based on your profile, goals, sport, and performance history. No two athletes receive the same plan.",
    keyPoints: [
      "Sport-specific exercise selection and periodization",
      "Dynamic difficulty scaling based on fitness level",
      "Goal-oriented programming (strength, endurance, hypertrophy)",
      "Consideration of available equipment and time constraints",
    ],
  },
  {
    icon: Activity,
    title: "Fatigue Tracking",
    gradient: "from-accent to-accent/50",
    description:
      "Monitor recovery in real-time through subjective wellness scores, sleep data, and performance trends. The system detects fatigue before it becomes a problem.",
    keyPoints: [
      "Daily wellness questionnaire (sleep, stress, soreness, mood)",
      "Cumulative fatigue load calculations",
      "Acute-to-chronic workload ratio monitoring",
      "Automated deload recommendations when needed",
    ],
  },
  {
    icon: Shield,
    title: "Risk Prevention",
    gradient: "from-chart-3 to-chart-3/50",
    description:
      "Intelligent overtraining detection and injury risk alerts help you train hard while staying safe. The AI continuously monitors for warning signs.",
    keyPoints: [
      "Overtraining syndrome early warning system",
      "Training load spike detection and alerts",
      "Muscle group balance analysis",
      "Personalized recovery protocol suggestions",
    ],
  },
  {
    icon: TrendingUp,
    title: "Progress Analytics",
    gradient: "from-chart-4 to-chart-4/50",
    description:
      "Comprehensive dashboards visualize every dimension of your athletic journey. Track strength gains, endurance improvements, body composition, and more.",
    keyPoints: [
      "Visual progress charts with trend analysis",
      "Personal records and milestone tracking",
      "Performance benchmarking against goals",
      "Exportable reports for coaches and medical professionals",
    ],
  },
  {
    icon: Calendar,
    title: "Adaptive Planning",
    gradient: "from-primary to-accent",
    description:
      "Your training plan is never static. After every session, the AI recalculates and adjusts upcoming workouts based on how you performed and recovered.",
    keyPoints: [
      "Post-session automatic plan recalibration",
      "Missed workout intelligent rescheduling",
      "Progressive overload management",
      "Seasonal and competition periodization",
    ],
  },
  {
    icon: Users,
    title: "Trainer Support",
    gradient: "from-accent to-chart-3",
    description:
      "Purpose-built tools for coaches to manage rosters, review athlete data, override AI suggestions, and communicate with their teams at scale.",
    keyPoints: [
      "Multi-athlete dashboard with alerts",
      "AI recommendation override capabilities",
      "Group and individual plan management",
      "In-app messaging and feedback tools",
    ],
  },
]

const dashboardFeatures = [
  {
    icon: BarChart3,
    label: "Performance Metrics",
  },
  {
    icon: HeartPulse,
    label: "Recovery Status",
  },
  {
    icon: AlertTriangle,
    label: "Risk Indicators",
  },
  {
    icon: LineChart,
    label: "Trend Analysis",
  },
  {
    icon: RefreshCw,
    label: "Adaptive Schedule",
  },
  {
    icon: UserCheck,
    label: "Trainer Oversight",
  },
]

export default function FeaturesPage() {
  return (
    <PageLayout>
      {/* Hero Section */}
      <section className="py-24 lg:py-32 relative overflow-hidden">
        <div className="absolute top-0 right-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-1/4 w-96 h-96 bg-accent/10 rounded-full blur-3xl" />

        <div className="container mx-auto px-4 lg:px-8 relative z-10">
          <div className="text-center max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-6">
              <span className="text-sm font-medium text-primary">
                Platform Features
              </span>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-balance">
              Everything You Need to{" "}
              <span className="gradient-text">Train Smarter</span>
            </h1>
            <p className="text-lg text-muted-foreground leading-relaxed max-w-2xl mx-auto">
              A complete AI-powered training ecosystem built for athletes who
              demand more from their workouts and coaches who want data-driven
              insights.
            </p>
          </div>
        </div>
      </section>

      {/* Feature Categories */}
      <section className="py-16 lg:py-24">
        <div className="container mx-auto px-4 lg:px-8">
          <div className="space-y-12 max-w-6xl mx-auto">
            {featureCategories.map((feature, index) => (
              <Card
                key={feature.title}
                className="bg-card/50 border-border/50 rounded-2xl overflow-hidden group card-hover"
              >
                <CardContent className="p-0">
                  <div
                    className={`flex flex-col ${
                      index % 2 === 1 ? "lg:flex-row-reverse" : "lg:flex-row"
                    }`}
                  >
                    {/* Icon & Title Side */}
                    <div className="lg:w-2/5 p-8 lg:p-10 flex flex-col justify-center relative overflow-hidden">
                      <div
                        className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-5`}
                      />
                      <div className="relative z-10">
                        <div
                          className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${feature.gradient} flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}
                        >
                          <feature.icon className="w-8 h-8 text-background" />
                        </div>
                        <h3 className="text-2xl md:text-3xl font-bold text-foreground mb-2">
                          {feature.title}
                        </h3>
                        <Badge variant="secondary" className="text-xs">
                          Core Feature
                        </Badge>
                      </div>
                    </div>

                    {/* Details Side */}
                    <div className="lg:w-3/5 p-8 lg:p-10 border-t lg:border-t-0 lg:border-l border-border/50">
                      <p className="text-muted-foreground leading-relaxed mb-6">
                        {feature.description}
                      </p>
                      <ul className="space-y-3">
                        {feature.keyPoints.map((point) => (
                          <li
                            key={point}
                            className="flex items-start gap-3 text-sm text-foreground"
                          >
                            <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                            <span>{point}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Dashboard Preview Section */}
      <section className="py-16 lg:py-24 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-accent/5" />
        <div className="container mx-auto px-4 lg:px-8 relative z-10">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <Badge variant="secondary" className="mb-4">
              Dashboard Preview
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-6 text-foreground">
              Your Command Center for{" "}
              <span className="gradient-text">Athletic Intelligence</span>
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              All your training data, insights, and recommendations unified in
              one powerful, intuitive dashboard.
            </p>
          </div>

          {/* Mock Dashboard */}
          <div className="max-w-5xl mx-auto">
            <Card className="bg-card/50 border-border/50 rounded-2xl overflow-hidden">
              <CardContent className="p-0">
                {/* Dashboard Header */}
                <div className="flex items-center gap-3 px-6 py-4 border-b border-border/50">
                  <div className="flex gap-1.5">
                    <div className="w-3 h-3 rounded-full bg-red-500/60" />
                    <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
                    <div className="w-3 h-3 rounded-full bg-green-500/60" />
                  </div>
                  <div className="flex-1 flex justify-center">
                    <div className="px-4 py-1 rounded-md bg-secondary/50 text-xs text-muted-foreground flex items-center gap-2">
                      <MonitorSmartphone className="w-3 h-3" />
                      app.masssport.ai/dashboard
                    </div>
                  </div>
                </div>

                {/* Dashboard Grid */}
                <div className="p-6 grid grid-cols-2 md:grid-cols-3 gap-4">
                  {dashboardFeatures.map((item) => (
                    <div
                      key={item.label}
                      className="flex flex-col items-center gap-3 p-6 rounded-xl bg-secondary/30 border border-border/30"
                    >
                      <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center">
                        <item.icon className="w-6 h-6 text-primary" />
                      </div>
                      <span className="text-sm font-medium text-foreground text-center">
                        {item.label}
                      </span>
                      {/* Mock data bars */}
                      <div className="w-full flex gap-1 justify-center">
                        {[40, 65, 50, 80, 55, 70, 90].map((h, i) => (
                          <div
                            key={i}
                            className="w-2 rounded-full bg-gradient-to-t from-primary to-accent"
                            style={{ height: `${h * 0.4}px` }}
                          />
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Quick Feature Grid */}
      <section className="py-16 lg:py-24">
        <div className="container mx-auto px-4 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-6 text-foreground">
              And <span className="gradient-text">Much More</span>
            </h2>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
            {[
              { icon: Zap, label: "Real-Time Alerts" },
              { icon: Target, label: "Goal Tracking" },
              { icon: HeartPulse, label: "Wellness Scores" },
              { icon: MonitorSmartphone, label: "Mobile Friendly" },
              { icon: RefreshCw, label: "Auto Sync" },
              { icon: UserCheck, label: "Role-Based Access" },
              { icon: BarChart3, label: "Custom Reports" },
              { icon: Shield, label: "Data Privacy" },
            ].map((item) => (
              <div
                key={item.label}
                className="flex flex-col items-center gap-3 p-5 rounded-xl glass group"
              >
                <item.icon className="w-6 h-6 text-primary group-hover:scale-110 transition-transform" />
                <span className="text-sm font-medium text-foreground text-center">
                  {item.label}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 lg:py-32 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-accent/10" />
        <div className="absolute top-1/2 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl -translate-y-1/2" />
        <div className="absolute top-1/2 right-1/4 w-96 h-96 bg-accent/20 rounded-full blur-3xl -translate-y-1/2" />

        <div className="container mx-auto px-4 lg:px-8 relative z-10">
          <div className="glass-card rounded-3xl p-8 md:p-12 lg:p-16 text-center max-w-4xl mx-auto">
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6 text-balance">
              Experience Every Feature{" "}
              <span className="gradient-text">Free for 14 Days</span>
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed mb-8 max-w-2xl mx-auto">
              Unlock the full power of AI-driven training. No credit card
              required. Cancel anytime.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/signup">
                <Button
                  size="lg"
                  className="bg-primary hover:bg-primary/90 text-primary-foreground px-8 h-14 text-base"
                >
                  Start Free Trial
                  <ArrowRight className="ml-2 w-5 h-5" />
                </Button>
              </Link>
              <Link href="/how-it-works">
                <Button
                  size="lg"
                  variant="outline"
                  className="border-border hover:bg-secondary h-14 text-base px-8"
                >
                  See How It Works
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </PageLayout>
  )
}
